version: '3.7'

services:
  cupom:
    build: "../cupom"
    container_name: cupom
    ports: 
      - "8000:8000"
    restart: always

  frete:
    build: "../frete"
    container_name: frete
    ports: 
      - "8001:8001"
    restart: always

  frontend:
    build: "."
    container_name: frontend
    ports: 
      - "3000:3000"
    restart: always


